Exception in thread Thread-6:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-21:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/software/python/anaconda/2020_11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "motif_assesment_euclidean.py", line 127, in assesment_duckery
    current_assesment = motif_assesment(motif1)
  File "motif_assesment_euclidean.py", line 104, in motif_assesment
    assesment_out('motifs_report_euc.txt', assesment, 'a')
  File "motif_assesment_euclidean.py", line 19, in assesment_out
    ot_f.write(', '.join(map(str, motif1['motif'])))
NameError: name 'motif1' is not defined
